spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-management-service
    username: root
    password: Huynguyen11102002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-management-service

server:
  port: 9003



